# Generated by Django 4.2.3 on 2023-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='users/images/user-default.png', upload_to='users/images/'),
        ),
    ]
