# Generated by Django 4.2.3 on 2023-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_user_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books/images/book-default.jpg', upload_to='users/images/'),
        ),
    ]
